" .config/nvim/init.vim

syntax enable
set shiftwidth=4
set smarttab
set tabstop=4
set softtabstop=4
set ignorecase
set incsearch
set hlsearch
set ruler
set number
set visualbell
set title
set wildmenu
set history=100
set foldmethod=indent
set foldnestmax=1
set termguicolors
set cursorline
set showcmd
set showmatch
set foldenable
set foldlevelstart=0
